"""empty message

Revision ID: 4cf3b166a382
Revises: 
Create Date: 2024-03-08 10:49:37.350916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf3b166a382'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_job_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('order_of_products', sa.String(length=100), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('end_of_production', sa.Date(), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('production_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_job_card_id', sa.Integer(), nullable=False),
    sa.Column('production_challenges', sa.Text(), nullable=True),
    sa.Column('quality_measurements', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['production_job_card_id'], ['production_job_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_reports')
    op.drop_table('users')
    op.drop_table('production_job_cards')
    # ### end Alembic commands ###
